---
- name: 'Configure and start distribution-container-registry'
  hosts: 'all'
  gather_facts: true
  become: true

  handlers:

    - name: 'Restart the distribution-container-registry service'
      ansible.builtin.service:
        name: 'distribution-container-registry'
        state: 'restarted'
      when:
        - 'not distribution_container_registry_service_started.changed | bool'

  tasks:

    - name: 'Create /etc/distribution/config.yml'
      ansible.builtin.template:
        src: 'etc_distribution_config.yml.j2'
        dest: '/etc/distribution/config.yml'
        owner: 'root'
        group: 'distribution-container-registry'
        mode: '660'
      notify:
        - 'Restart the distribution-container-registry service'

    - name: 'Start the distribution-container-registry service'
      ansible.builtin.service:
        name: 'distribution-container-registry'
        state: 'started'
      register: distribution_container_registry_service_started

    - name: 'Enable the distribution-container-registry service'
      ansible.builtin.service:
        name: 'distribution-container-registry'
        enabled: true
